# Generated by Django 5.2.11 on 2026-02-19 23:49

from django.db import migrations, models

def transfer_priority_to_importance(apps, schema_editor):
    Todo = apps.get_model('todos', 'Todo')

    for todo in Todo.objects.all():
        if hasattr(todo, 'priority') and todo.priority is not None:
            mapping = {1: 'Low', 2: 'Medium', 3: 'High'}
            todo.importance = mapping.get(todo.priority, 'Low')  # Valeur par défaut au cas où
            todo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_person_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.CharField(
                max_length=10,
                choices=(('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')),
                blank=True,
                null=True
            ),
        ),
        migrations.RunPython(
            transfer_priority_to_importance,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
